apiVersion: apps/v1
kind: Deployment
metadata:
  name: hygieia-ui
  labels:
    app: hygieia-ui
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: hygieia-ui
  template:
    metadata:
      labels:
        name: hygieia-ui
        app: hygieia-ui
    spec:
      hostname: hygieia-ui
      containers:
      - name: hygieia-ui
        image: 7078555411/hygieia-ui
        env:
        - name: API_HOST
          value: hygieia-svc
        - name: API_PORT
          value: 8080
        resources:
            limits:
              cpu: 15m
              memory: 55Mi
            requests:
              cpu: 10m
              memory: 50Mi
        ports:
        - containerPort: 80  
