apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: hygieia-ui
    spec:
  type: NodePort
  ports:
  - name: 80
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: hygieia-ui
